### ISSUE TITLE
Content Moderator Timeout Issue

### ISSUE THREAD

**Issue by stharmar-hitachi** [dev-mastery/comments-api#44]
Hello @arcdev1 and thank you so much for the sample code and the amazing videos.

I am facing signup issue while creating this reference url "https://contentmoderator.cognitive.microsoft.com" which you given.

I got this below error always, even I have good internet connection.

![content_moderator_timeout_issue](https://user-images.githubusercontent.com/20662634/94281308-16a9d080-ff6c-11ea-9d1f-5601b8820129.png)

Can you suggest me, how to resolve on this same. Thanks in advance sir

**Comment by arcdev1** [comment]
@stharmar-hitachi thanks so much for your kind words.

I did some investigation and I can not get the Central India region to work either. Canada Central (where I am) works but I don't think that helps you very much. If you have access to a support plan with Microsoft Azure you can open a ticket. Otherwise, you may want to try a different region (e.g. https://eastasia.contentmoderator.cognitive.microsoft.com works).
